spring:
  application:
    name: config-meow
  config:
    import: classpath:you-cant-see-that.yml
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:ENC(AdWk4PSD8S3YHvL824vcUWPkYgVIdSRID1Sy7d2xGa+/WoU0PHMTXvVyk+n7LjQAeidxhRDRQSw9ilmYnY5eef5Tb+1lP4LSa+C5up64Sal7lEqgXbTvalO50Yrsn+mgUGoPJ5DfJ8bETsD35HPKNc/AhcxbzeJHFxrHKhYMsI8EJRFhpzho81HAUd6ARO1l2Ugryj+nbXfWMIgD7PZ6Uo32hHOYzxivRN18YiKmSHU=)}
    username: ${MYSQL_USERNAME:ENC(c4DGmvubXBa9qNXjzUd7muOmW5YNnmMy)}
    password: ${MYSQL_PASSWORD:ENC(yM1T6o/RuGGOBTafds7gEjNzWRCc1B2VeJLSjuNpKmw=)}
    
    # Druid连接池配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 监控统计用的filter:stat，日志用的filter:log4j，防御sql注入的filter:wall
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin123
        allow: ENC(AZYdREZPfNDtJedm4TvKS+VQkyRvdtfFTZ5EVMo7F9w=)

# MyBatis Plus配置
mybatis-plus:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 搜索指定包别名
  type-aliases-package: io.github.timemachinelab.entity
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    # 开启缓存
    cache-enabled: false
    # 日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 主键策略
      id-type: AUTO
      # 逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0